GARUDA_MOKKA_URL="https://gitlab.com/garuda-linux/themes-and-settings/settings/garuda-mokka.git"
GARUDA_COMMON_URL="https://gitlab.com/garuda-linux/themes-and-settings/settings/garuda-common-settings.git"
GARUDA_CATPPUCCIN_URL="https://gitlab.com/garuda-linux/website/website-catppuccin.git"
GARUDA_PKGBUILDS_URL="https://gitlab.com/garuda-linux/pkgbuilds.git"
